### ISSUE TITLE
konduit-serving-tensorflow: ARM64/aarch64 support

### ISSUE THREAD

**Issue by AlexDBlack** [KonduitAI/konduit-serving#338] opened 2020-05-23 13:15 UTC
The version of TensorFlow Java that we are using (1.15.0, the latest version available on Maven) only has x86_64 support:
* For CPU: Windows, Linux and Mac
* For CUDA: Windows and Linux

https://repo1.maven.org/maven2/org/tensorflow/libtensorflow_jni/1.15.0/libtensorflow_jni-1.15.0.jar
https://repo1.maven.org/maven2/org/tensorflow/libtensorflow_jni_gpu/1.15.0/libtensorflow_jni_gpu-1.15.0.jar

Consequently, running konduit-serving-tensorflow tests on ARM64 (Jetson Nano) gives the following:
```
java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS: linux, architecture: aarch64. See https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java/README.md for possible solutions (such as building the library from source). Additional information on attempts to find the native library can be obtained by adding org.tensorflow.NativeLibrary.DEBUG=1 to the system properties of the JVM.
 at org.tensorflow.NativeLibrary.load(NativeLibrary.java:77)
 at org.tensorflow.TensorFlow.init(TensorFlow.java:67)
 at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:82)
 at org.tensorflow.Tensor.<clinit>(Tensor.java:838)
 at ai.konduit.serving.models.tensorflow.format.TensorFlowConverters$SerializedToTensorFlowConverter.convert(TensorFlowConverters.java:70)
 at ai.konduit.serving.models.tensorflow.format.TensorFlowConverters$SerializedToTensorFlowConverter.convert(TensorFlowConverters.java:55)
 at ai.konduit.serving.pipeline.impl.data.ndarray.BaseNDArray.getAs(BaseNDArray.java:47)
 at ai.konduit.serving.models.tensorflow.TestArrayConversion.testConversion(TestArrayConversion.java:73)
```

**Comment by jaredzhu** [comment] 2021-05-19 06:07
how to solve this problem  to support aarch64？？？

**Comment by agibsonccc** [comment] 2021-05-19 08:16
@jaredzhu  we actually do have builds that will be ready. Do you mind posting what you're trying to do over on the forums at https://community.konduit.ai?

**Comment by jaredzhu** [comment] 2021-05-19 08:57
> @jaredzhu we actually do have builds that will be ready. 

so, where could I get the version for aarch64?

>Do you mind posting what you're trying to do over on the forums at https://community.konduit.ai?

ok， i'll post it later

**Comment by agibsonccc** [comment] 2021-05-21 04:19
@jaredzhu  never heard from you. The builds need to be built from source but are possible with the latest snapshots.  Regarding your TF use case, the bindings for the underlying software actually don't exist there:
https://repo1.maven.org/maven2/org/bytedeco/tensorflow/1.15.5-1.5.5/

Execution using konduit-serving would require either using python execution or our model import. If you can emphasize your use case a bit, I'd be happy to help you.

**Comment by RanFang66** [comment] 2022-12-13 14:04
Does anyone solve this problem? It's too hard for me to build from source in aarch64/arm64.

**Comment by agibsonccc** [comment] 2022-12-13 21:57
@RanFang66  the tensorflow bindings on this are 1.x at this point. Are you ok with that?

**Comment by agibsonccc** [comment] 2022-12-15 08:06
@RanFang66 yeah it's not available for that architecture. In order to run things on the pi you'll have to switch libraries or try out importing the model and running it using our arm runtime. If you want, feel free to post on our forums: https://community.konduit.ai/ I'm closing this as this is not a bug and I will not be supporting building an old version of an external library from source.

**Closed by agibsonccc** 2022-12-15 08:06 UTC
